server:
  port: 8083
  error:
    include-stacktrace: never

spring:
  application:
    name: "pokedex-tabletypes"

services:
  pokemon-type:
    main-path: "/api/pokedex/type"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8001/eureka

feign:
  clients:
    type:
      url: "https://pokeapi.co"
      resource: "/api/v2/type/{name}/"
      name: "pokemon-type"
