server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  application:
    name: "pokedex-tabletypes"

services:
  pokemon-type:
    main-path: "/api/pokedex/type"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

feign:
  clients:
    type:
      url: "https://pokeapi.co"
      resource: "/api/v2/type/{name}/"
      name: "pokemon-type"

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      pokemon-type-client:
        base-config: shared
