server:
  port: 8082

spring:
  application:
    name: "pokedex-strategy"

services:
  pokemon-strategy:
    main-path: "/api/pokedex/strategy"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8001/eureka

feign:
  clients:
    type:
      resource: "/api/pokedex/type"
      name: "POKEDEX-TABLETYPES"
    info:
      resource: "/api/pokedex/info"
      name: "POKEDEX-INFO"

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      pokemon-info-client:
        base-config: shared
      pokemon-tabletypes-client:
        base-config: shared
